// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1:string):Promise<void>;

export function Del(arg1:number):Promise<void>;

export function GetLen():Promise<number>;

export function GetMsg(arg1:number):Promise<string>;

export function GetMsgs():Promise<Array<string>>;

export function KillSelf():Promise<void>;

export function MinWindow():Promise<void>;

export function Read():Promise<void>;

export function RedomSay():Promise<string>;

export function Set(arg1:number,arg2:string):Promise<void>;

export function SetH(arg1:number):Promise<void>;

export function Write():Promise<void>;
