// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['App']['Add'](arg1);
}

export function Del(arg1) {
  return window['go']['main']['App']['Del'](arg1);
}

export function GetLen() {
  return window['go']['main']['App']['GetLen']();
}

export function GetMsg(arg1) {
  return window['go']['main']['App']['GetMsg'](arg1);
}

export function GetMsgs() {
  return window['go']['main']['App']['GetMsgs']();
}

export function KillSelf() {
  return window['go']['main']['App']['KillSelf']();
}

export function MinWindow() {
  return window['go']['main']['App']['MinWindow']();
}

export function Read() {
  return window['go']['main']['App']['Read']();
}

export function RedomSay() {
  return window['go']['main']['App']['RedomSay']();
}

export function Set(arg1, arg2) {
  return window['go']['main']['App']['Set'](arg1, arg2);
}

export function SetH(arg1) {
  return window['go']['main']['App']['SetH'](arg1);
}

export function Write() {
  return window['go']['main']['App']['Write']();
}
